spring:
  application:
    name: erp-manager
  datasource:
    url: ${DATASOURCE_URL:jdbc:sqlserver://localhost;databaseName=erp-manager;encrypt=true;trustServerCertificate=true}
    username: ${DATASOURCE_USERNAME:sa}
    password: ${DATASOURCE_PASSWORD:123456}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://localapi.digitalams.net/auth/realms/erp-manager-dev
logging:
  level:
    org:
      springframework:
        security: INFO

server:
  port: 8085
app:
  security:
    client-id: onboarding_manager
    client-secret: WaYsKI6duiVsPC6A1hlJ8QP2nfRLO1D5
    iam-host: https://localapi.digitalams.net/auth
    realm: erp-manager-dev
  iam-host: https://localapi.digitalams.net/auth